services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-monetization-gateway:latest
    container_name: api-monetization-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379,abortConnect=false
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ApiGatewayDb;User Id=sa;Password=Your_strong_password123!;TrustServerCertificate=true;
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - sqlserver
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data:
  sqlserver-data:
